services:
  - type: web
    name: sonrisas-aldia-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromBuild: true
      - key: DB_HOST
        value: interchange.proxy.rlwy.net
      - key: DB_PORT
        value: "12471"
      - key: DB_DATABASE
        value: bd_dental
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: IgpNoItFsvikmXDMsSsrmrvpaRTKlYed

  - type: cron
    name: laravel-reminders
    schedule: "* * * * *"
    buildCommand: "composer install --no-dev --ignore-platform-reqs"
    startCommand: "php artisan reminders:send"